---
galaxy_info:
  author: "Student"
  description: "Роль для установки веб-сервера Apache"
  company: "Netology"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - web
    - apache
    - httpd
    - webserver

dependencies: []
